---

rhdh_backend_secret: "{{ secrets_dir + '/rhdh_backend_secret' }}"
rhdh_github_app_app_id: "{{ secrets_dir + '/rhdh_github_app_app_id' }}"
rhdh_github_app_client_id: "{{ secrets_dir + '/rhdh_github_app_client_id' }}"
rhdh_github_app_client_secret: "{{ secrets_dir + '/rhdh_github_app_client_secret' }}"
rhdh_github_app_webhook_url: "{{ secrets_dir + '/rhdh_github_app_webhook_url' }}"
rhdh_github_app_webhook_secret: "{{ secrets_dir + '/rhdh_github_app_webhook_secret' }}"
rhdh_github_app_private_key: "{{ secrets_dir + '/rhdh_github_app_private_key' }}"
rhdh_ghe_access_token: "{{ secrets_dir + '/rhdh_ghe_access_token' }}"
