---

ansible_host: netsvcs.lab.gmarcy.com
ansible_ssh_host: netsvcs.lab.gmarcy.com
gathering_roles:
- gmarcy.ansible.setup_ansible_host
- gmarcy.ansible.gather_host_facts
prepare_host_roles:
- gmarcy.ansible.add_remote_ssh_access:
    authorized_key_name: work_laptop
install_disk: nvme0n1
ipmi_info:
  interface: none
efibootmgr:
  ipxe_bootdev: '2'
ipxe_mac_address: 34-1a-4c-03-45-23
csi_lvm_device: /dev/nvme0n1p6
