---

- name: Add ssh access to remote hosts
  hosts: remote_hosts
  gather_facts: false
  pre_tasks:
  - assert:
      that: authorized_key_name is defined and hostvars['localhost-facts']['authorized_keys'][authorized_key_name] is defined
  roles:
  - role: add_authorized_key_from_keypair
    ssh_user: "{{ ssh_username | default(hostvars['playbook-facts'].remote_user) }}"
    ssh_pubkey: "{{ hostvars['localhost-facts'].authorized_keys[authorized_key_name].pubkey }}"
    ssh_comment: "{{ hostvars['localhost-facts'].authorized_keys[authorized_key_name].comment }}"
    ssh_become_user: "{{ become_user or omit }}"
