---

- name: "Gather cluster facts from {{ hostvars['cluster-facts']['cluster_provisioner'] | default('cluster_provisioner') }}"
  hosts: "{{ hostvars['cluster-facts']['cluster_provisioner'] | default('cluster_provisioner') }}"
  gather_facts: false
  tags: cluster_facts
  roles:
  - role: check_playbook_terminated
  tasks:
  - name: "include_role: {{ cluster_facts_role }}"
    include_role:
      name: "{{ cluster_facts_role }}"

- name: Generate cluster secrets using cluster_secrets_role when requested
  hosts: playbook_secrets
  gather_facts: false
  vars:
    cluster_secrets_role: "{{ hostvars['cluster-facts']['cluster_secrets_role'] or omit }}"
  roles:
  - role: check_playbook_terminated
  tasks:
  - name: "include_role: {{ cluster_secrets_role | default('skipped') }}"
    include_role:
      name: "{{ cluster_secrets_role }}"
    when: cluster_secrets_role | default('') | length > 0

- name: Gather host facts from all nodes
  hosts: all_nodes
  gather_facts: false
  tags: cluster_facts
  roles:
  - role: check_playbook_terminated
  - role: gather_host_facts
    gather_packages_info: false
    gather_services_info: false
