---

- name: Install IBM Zen Operator and Operands into cluster
  hosts: was_automation
  gather_facts: false
  tags: was_automation
  roles:
  - role: create_target_operand_request
    api_key: "{{ hostvars['cluster-facts']['api_key'] | default(omit) }}"
    kubeconfig_path: "{{ hostvars['cluster-facts']['kubeconfig_path'] }}"
    target_operand_request_name: 'operand-request-zen'
    target_operand_request_namespace: "{{ was_automation_namespace }}"
    target_operand_name: 'ibm-platformui-operator'
  - role: install_zen_operands
    api_key: "{{ hostvars['cluster-facts']['api_key'] | default(omit) }}"
    kubeconfig_path: "{{ hostvars['cluster-facts']['kubeconfig_path'] }}"
    target_namespace: "{{ was_automation_namespace }}"
    registry_namespace: "{{ common_service_namespace }}"
    zen_storage_class: "{{ hostvars['cluster-storage']['default_storage_class'] }}"
    zen_block_class: "{{ hostvars['cluster-storage']['default_block_class'] }}"
