---

- name: Install IBM Events Operator and Operands into cluster
  hosts: was_automation
  gather_facts: false
  tags: was_automation
  roles:
  - role: create_target_operand_request
    api_key: "{{ hostvars['cluster-facts']['api_key'] | default(omit) }}"
    kubeconfig_path: "{{ hostvars['cluster-facts']['kubeconfig_path'] }}"
    target_operand_request_name: 'operand-request-events'
    target_operand_request_namespace: "{{ was_automation_namespace }}"
    target_operand_name: 'ibm-events-operator'
  - role: install_events_operands
    api_key: "{{ hostvars['cluster-facts']['api_key'] | default(omit) }}"
    kubeconfig_path: "{{ hostvars['cluster-facts']['kubeconfig_path'] }}"
    target_namespace: "{{ was_automation_namespace }}"
    registry_namespace: "{{ common_service_namespace }}"
