---

- name: "Request a cluster from {{ hostvars['cluster-facts']['cluster_provisioner'] }}"
  hosts: "{{ hostvars['cluster-facts']['cluster_provisioner'] }}"
  gather_facts: false
  tasks:
  - name: "include_role: {{ provisioning_role }}"
    include_role:
      name: "{{ provisioning_role }}"

- name: "Prepare nodes using node_prepare_role when requested"
  hosts: all_nodes
  gather_facts: false
  roles:
  - role: check_playbook_terminated
  tasks:
  - name: "include_role: {{ node_prepare_role | default('skipped') }}"
    include_role:
      name: "{{ node_prepare_role }}"
    when: node_prepare_role | default('') | length > 0

- name: Generate cluster secrets using cluster_secrets_role when requested
  hosts: playbook_secrets
  gather_facts: false
  vars:
    cluster_secrets_role: "{{ hostvars['cluster-facts']['cluster_secrets_role'] or omit }}"
  roles:
  - role: check_playbook_terminated
  tasks:
  - name: "include_role: {{ cluster_secrets_role | default('skipped') }}"
    include_role:
      name: "{{ cluster_secrets_role }}"
    when: cluster_secrets_role | default('') | length > 0

- name: Gather facts from all nodes
  hosts: all_nodes
  gather_facts: false
  roles:
  - role: check_playbook_terminated
  - role: setup_ansible_host
  - role: gather_host_facts
    gather_packages_info: false
    gather_services_info: false

- name: Setup services running in infra node
  hosts: infra_node
  gather_facts: false
  vars:
    deploy_infra_services: "{{ hostvars[groups[hostvars['cluster-facts']['cluster_provisioner']][0]]['deploy_infra_services'] }}"
  roles:
  - role: check_playbook_terminated
  - role: services_enable_linger
    when: deploy_infra_services
  - role: infra_install_creds
    when: deploy_infra_services
  - role: infra_install_registry
    when: deploy_infra_services
  - role: infra_install_registry_proxy
    when: deploy_infra_services
  - role: infra_install_haproxy
    when: deploy_infra_services

- name: "Provision nodes using node_provisioning_role when requested"
  hosts: all_nodes
  gather_facts: false
  vars:
    node_provisioning_role: "{{ hostvars[groups[hostvars['cluster-facts']['cluster_provisioner']] | first]['k8s_node_provisioning_role'] or omit }}"
  roles:
  - role: check_playbook_terminated
  tasks:
  - name: "include_role: {{ node_provisioning_role | default('skipped') }}"
    include_role:
      name: "{{ node_provisioning_role }}"
    when: node_provisioning_role | default('') | length > 0
