---

all_nodes:
cluster_hosts:

ungrouped:
  hosts:
    assisted-install:
      provisioning_role: 'cluster_request_assisted'
      deprovisioning_role: 'cluster_cleanup_assisted'
      cluster_facts_role: 'cluster_gather_facts_assisted'
    cluster-facts:
      cluster_provisioner: 'assisted-install'
      inv_cluster_description: 'OpenShift Cluster'
      inv_cluster_single_node: true
      inv_kubernetes_distro: openshift
      inv_openshift_distro: okd
      inv_openshift_version: '4.13'
    cluster-storage:
      storage_provisioner: 'nfslocal'
      provisioning_role: 'storage_deploy_nfslocal'
      deprovisioning_role: 'storage_remove_nfslocal'
      inv_default_storage_class: "{{ nfslocal_storage_class }}"
      inv_default_block_class: "{{ nfslocal_block_class }}"
