---

all:
  children:
    cluster_operators:
      hosts:
        cluster-operators:
          operators_to_deploy:
          - name: cert-manager
            namespace: community-cert-manager
            catalog: community-operators
    common_services:
      hosts:
        common-services:
          inv_common_service_catalog_source_name: 'opencloud-operators'
          inv_common_service_catalog_source_display_name: 'IBMCS Test Operators'
          inv_common_service_catalog_source_image: "{{ inv_common_service_catalog_source_image_cs4 }}"
          inv_common_service_catalog_source_image_tag: "{{ inv_common_service_catalog_source_image_tag_cs4 }}"
    integration_platform:
      hosts:
        integration-platform:
          inv_cp4i_catalog_source_name: 'ibm-integration-platform-navigator-aas-catalog'
          inv_cp4i_catalog_source_display_name: 'IBM Integration Platform Navigator-aaS Catalog'
          inv_cp4i_catalog_source_image: "{{ inv_cp4i_catalog_source_image_cs4 }}"
          inv_cp4i_catalog_source_image_tag: "{{ inv_cp4i_catalog_source_image_tag_cs4 }}"
          inv_cp4i_operator_namespace: 'cp4i'
  vars:
    cloudpak_tenant_namespace: "{{ hostvars['integration-platform'].cp4i_namespace }}"
    cloudpak_tenant_operator_group: "{{ hostvars['integration-platform'].cp4i_operator_group }}"
