---

ungrouped:
  hosts:
    cluster-facts:
      cluster_provisioner: 'fyre-provisioner'
      inv_cluster_description: 'OpenShift Cluster'
      inv_cluster_domain: cp.fyre.ibm.com
      inv_kubernetes_distro: openshift
      inv_openshift_distro: ocp
      inv_openshift_version: '4.15.0'
    cmdline-facts:
    fyre-provisioner:
      deploy_infra_services: false
      inv_fyre_ocptype: ocpplus
      inv_fyre_site: rtp
      inv_fyre_group_id: 52
    localhost-facts:
      inv_ssh_keytype: rsa
      ssh_keypair_name: fyre
      ssh_keypairs:
        fyre:
          path_prefix: ""
          secret: "fyre_ssh_key"
    playbook-facts:
    playbook-secrets:
      inv_secrets_dir: "{{ lookup('env', 'HOME') + '/.ssh/.ansible/.secrets' }}"
