---

all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    cluster_facts:
      hosts:
        cluster-facts:
          inv_cluster_domain: clusters.lab.gmarcy.com
          inv_network_cidr: 192.168.222.0/24
    cluster_hosts:
      vars:
        host_domain: lab.gmarcy.com
    localhost_facts:
      hosts:
        localhost-facts:
          inv_ssh_keytype: ed25519
          ssh_keypair_name: homelab
          ssh_keypairs:
            homelab:
              path: "{{ local_home + '/.ssh/homelab_id_' + ssh_keytype }}"
              secret: "homelab_ssh_key"
            netsvcs:
              path: "{{ local_home + '/.ssh/netsvcs_id_' + ssh_keytype }}"
              secret: "netsvcs_ssh_key"
            setup_host:
              path: "{{ local_home + '/.ssh/setup_id_' + ssh_keytype }}"
              secret: "setup_ssh_key"
          authorized_keys:
            homelab:
              pubkey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAsdgW20NtVSpXRSmC5cjEKTN+p9Ju01EdPYHdtwqmyp"
              comment: "homelab@gmarcy.com"
            netsvcs:
              pubkey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAIiz06kwpyVunkLvCJLddRxluoxIE/Cd2mw/8klX+JV"
              comment: "ansible-automation netsvcs-ssh-key"
            setup_host:
              pubkey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM8MzJQs6hb6BP6R85NuVCFvhb0SpQaS+t6tOJmv3sN5"
              comment: "ansible-automation setup-ssh-key"
            work_laptop:
              pubkey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBX9EpTxWQtnROTX+Nw/EfpQv7OPnIRQj32ToUKOLKhB"
              comment: "access to lab.gmarcy.com from work laptop"
    playbook_secrets:
      hosts:
        playbook-secrets:
          inv_secrets_dir: "{{ lookup('env', 'HOME') + '/.ssh/.ansible/.secrets' }}"
    services_facts:
      hosts:
        services-facts:
          deployments:
            "network-services":
            - services_enable_linger
            - services_enable_remote_podman
            - services_deploy_podman_pod
            - services_deploy_netbootxyz
