---

ungrouped:
  hosts:
    cluster-facts:
      host_domain: lab.gmarcy.com
      inv_cluster_domain: clusters.lab.gmarcy.com
      inv_network_cidr: 192.168.222.0/24
    localhost-facts:
      inv_ssh_keytype: ed25519
      ssh_keypair_name: homelab
      ssh_keypairs:
        homelab:
          path_prefix: "homelab_"
          secret: "homelab_ssh_key"
        setup_host:
          path_prefix: "setup_"
          secret: "setup_ssh_key"
    playbook-facts:
      authorized_keys:
        homelab:
          pubkey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAsdgW20NtVSpXRSmC5cjEKTN+p9Ju01EdPYHdtwqmyp"
          comment: "homelab@gmarcy.com"
        setup_host:
          pubkey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM8MzJQs6hb6BP6R85NuVCFvhb0SpQaS+t6tOJmv3sN5"
          comment: "ansible-automation setup-ssh-key"
        work_laptop:
          pubkey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBX9EpTxWQtnROTX+Nw/EfpQv7OPnIRQj32ToUKOLKhB"
          comment: "access to lab.gmarcy.com from work laptop"
      authorized_key_name: work_laptop
    playbook-secrets:
      inv_secrets_dir: "{{ lookup('env', 'HOME') + '/.ssh/.ansible/.secrets' }}"
