---

all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    all_nodes:
      hosts:
        netsvcs:
          ansible_connection: "ssh"
          ansible_host: "netsvcs.lab.gmarcy.com"
          ansible_ssh_user: "core"
          cluster_role: "master"
          fqdn: "netsvcs.lab.gmarcy.com"
          privateip: ""
          publicip: "192.168.222.253"
          short_hostname: "netsvcs"
    cluster_nodes:
      hosts:
        netsvcs:
    infra_node:
    master_nodes:
      hosts:
        netsvcs:
    worker_nodes:
    localhost_facts:
      hosts:
        localhost-facts:
          ssh_keypair_name: netsvcs
    cluster_facts:
      hosts:
        cluster-facts:
          cluster_provisioner: 'hosted_provisioner'
          inv_cluster_description: 'Kubernetes K3S Cluster'
          inv_cluster_domain: clusters.lab.gmarcy.com
          inv_kubernetes_distro: k3s
          inv_kubernetes_version: '1.28'
          k8s_k3s_registries_template: |
            configs:
              "docker.io":
                auth:
                  username: {{ lookup('unvault', hostvars['playbook-secrets']['docker_io_user']) | trim }}
                  password: {{ lookup('unvault', hostvars['playbook-secrets']['docker_io_password']) | trim }}
                tls:
                  insecure_skip_verify: true
    hosted_provisioner:
      hosts:
        hosted-provisioner:
          provisioning_role: 'cluster_request_hosted'
          deprovisioning_role: 'cluster_cleanup_hosted'
          cluster_facts_role: 'cluster_gather_facts_hosted'
          deploy_infra_services: false
          vars_inventory:
            k8s_version: 1.28.2
            k8s_engine: k3s
            k8s_inf_create_node: false
            k8s_master_nodes: 1
            k8s_worker_nodes: 0
    cluster_operators:
      hosts:
        cluster-operators:
          inv_operators_namespace: operators
          inv_community_operators_catalog_source_name: operatorhubio-catalog
          inv_community_operators_catalog_source_namespace: olm
          inv_ibm_operator_catalog_source_namespace: olm
          operators_to_deploy:
          - name: argocd-operator
            namespace: operators
            catalog: community-operators
            operands_role: install_argocd_operands
            config:
              env:
              - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
                value: argocd
    cluster_storage:
      hosts:
        cluster-storage:
          storage_provisioner: 'topolvm'
          provisioning_role: 'storage_deploy_topolvm'
          deprovisioning_role: 'storage_remove_topolvm'
          inv_default_storage_class: "{{ topolvm_storage_class }}"
          inv_default_block_class: "{{ topolvm_block_class }}"
