---

- name: Enable all ingress access within namespace through NetworkPolicy
  kubernetes.core.k8s:
    api_key: "{{ api_key | default(omit) }}"
    kubeconfig: "{{ kubeconfig_path }}"
    api_version: networking.k8s.io/v1
    kind: NetworkPolicy
    name: allow-all-ingress-policy
    namespace: "{{ target_namespace }}"
    definition:
      spec:
        podSelector: {}
        ingress:
          - {}
        policyTypes:
          - Ingress

- name: Create subscription for singlenamespace or all namespaces operator
  block:

    - name: Create Subscription
      include_role:
        name: create_target_subscription
      vars:
        target_operator_name: "{{ was_automation_operator_name }}"
        target_operator_namespace: "{{ wsa_operator_namespace }}"
        target_operator_labels: "{{ wsa_operator_labels or omit }}"
        target_operator_channel: "{{ was_automation_operator_channel or omit }}"
        target_catalog_source_name: "{{ was_automation_catalog_source_name }}"
        target_catalog_source_namespace: "{{ was_automation_catalog_source_namespace }}"
      register: _result

  vars:
    wsa_operator_namespace: "{{ target_namespace if operator_singlenamespace else was_automation_operator_namespace }}"
    wsa_operator_label_key: "{{ 'operators.coreos.com/' + was_automation_operator_name + '.' + wsa_operator_namespace }}"
    wsa_operator_labels: "{{ [{'key': wsa_operator_label_key, 'value': '' }] | items2dict }}"

- name: Wait for WSA operator controller manager
  kubernetes.core.k8s_info:
    api_key: "{{ api_key | default(omit) }}"
    kubeconfig: "{{ kubeconfig_path }}"
    kind: Deployment
    name: websphere-automation-operator-controller-manager
    namespace: "{{ target_namespace if operator_singlenamespace else was_automation_operator_namespace }}"
    wait: true
    wait_condition:
      type: Available
    wait_sleep: 20
    wait_timeout: 300
  register: _result
