---

- import_playbook: gmarcy.ansible.gather_playbook_facts
- import_playbook: gmarcy.ansible.gather_cluster_facts
- import_playbook: ../plays/install_operator_lifecycle_manager.yml
- import_playbook: ../plays/install_cluster_operators.yml
